name: Run test.py
description: composite action to run a local Python

inputs:
  height:
    required: true
  weight:
    required: true

runs:
  using: composite
  steps:
    - name: test script
      run: python bmi.py
      shell: bash
      env:
        HEIGHT: ${{ inputs.height }}
        WEIGHT: ${{ inputs.weight }}
