name: Run Tests  # ワークフローの名前

on:
  push:  # pushイベントを追加
    branches:
      - main  # mainブランチへのpushを対象
  pull_request:  # PRイベントも継続して対象にする
    types:
      - closed  # PRが閉じられたとき（マージ or クローズ）
    branches:
      - main  # mainブランチへのPRのみ対象

jobs:
  python:
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3  # リポジトリのコードをチェックアウト

      - uses: ./.github/actions/run-test-action  # 自作アクション呼び出し
        with:
          height: 250
          weight: 65
